name: interp-autoreg
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jags
  - pip:
    - jax
    - jupyterlab
    - jupyter_contrib_nbextensions
    - matplotlib
    - numba
    - numba-scipy
    - numpy
    - pyjags
    - pymc
    - scikit-learn
    - scipy
    - tqdm
